version: '3.8'
services:
  meli-price-tracker:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${CONTAINER_APP_PORT}"
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
    networks:
      - ${NETWORK}
    environment:
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

networks:
  backend:
    external:
      name: ${EXTERNAL_NETWORK}