version: '3.8'
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${LOCAL_APP_PORT}:${CONTAINER_APP_PORT}"
    networks:
      - ${NETWORK}
    environment:
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

networks:
  backend:
    external:
      name: ${EXTERNAL_NETWORK}