version: '3.8'
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${LOCAL_APP_PORT}:${CONTAINER_APP_PORT}"
    networks:
      - ${NETWORK}
    environment:
      - MONGO_URI=mongodb://${DB_CONTAINER_NAME}:${DB_PORT}/${DB_NAME}
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    container_name: ${DB_CONTAINER_NAME}
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - mongo-data:/data/db
    ports:
      - "${DB_LOCAL_PORT}:${DB_CONTAINER_PORT}"
    networks:
      - ${NETWORK}
networks:
  backend:
    external:
      name: ${EXTERNAL_NETWORK}

volumes:
  mongo-data:
